### ISSUE TITLE
Uso de tipos de libreria externas

### ISSUE THREAD

**Issue by DFaouaz** [Spicy-Noodles-Studio/Gaia#10]
Ahora mismo, casi todos los motores o componentes utilizan tipos de las librerias que se usan.
Hay que hacer nuestros propios nombres de tipos (con un typedef **NO** sirve). Pero nombres de otras librerias no deberian de verse a nivel de usuario. Hay que encapsular todos los tipos que creamos que se van a usar en el juego por el usuario

**Comment by argarc03** [comment]
Saludos,
esto está "hechísimo" ya.
No hay más qué hacer.
Issue cerrado.
