### ISSUE TITLE
Falsos positivos

### ISSUE THREAD

**Issue by DFaouaz** [Spicy-Noodles-Studio/Gaia#17]
Parece que la interfaz de CEGUI deja falsos positivos en memory leaks.
Investigad mas a fondo.

**Comment by argarc03** [comment]
Buenas tardes,
hemos investigado a fondo lo de CEGUI y parece ser que sus
desarrolladores son un poco ineptos.
Me temo que tengo que decirle que se va a quedar así.
Gracias por tanto, perdón por tan poco.
