### ISSUE TITLE
CUIDADO CON LOS TIPOS DEVUELTOS

### ISSUE THREAD

**Issue by DFaouaz** [Spicy-Noodles-Studio/Gaia#24]
Cuidado con hacer que todo devuelva referencias constantes.
Si se devuelve una referencia a un espacio de memoria creado localmente en una función, solo es licito devolverlo si se asegura que desde fuera se va a hacer una copia o referencia al valor devuelto.
Lo mejor, para quitarnos problemas es devolver una copia.

MUCHO CUIDADO, HAY QUE REVISAR TODO EL CÓDIGO

**Comment by argarc03** [comment]
Hola, Dany:
Le comento que hemos revisado todo el código con éxito y ya está todo limpio.
Gracias por informar el problema.

Un saludo.
"Por un código más spicy y menos noodle" - Spicy Noodles Team
